spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/${UPLOADER_DB_NAME}
    username: ${UPLOADER_DB_USER}
    password: ${UPLOADER_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "shared.events"

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_INTERNAL_ISSUER_URI:http://localhost:9999/realms/dev}

finpasser:
  storage:
    endpoint: ${MINIO_ENDPOINT}
    access-key: ${MINIO_ACCESS_KEY}
    secret-key: ${MINIO_SECRET_KEY}
    bucket-name: ${MINIO_BUCKET}

security:
  enabled: true
  cors:
    allowed-origins:
      - http://localhost:3000
    allow-credentials: true

keycloak:
  validation:
    enabled: ${KEYCLOAK_VALIDATION_ENABLED:true}
    token-url: ${KEYCLOAK_INTERNAL_TOKEN_URL:}
    users-url: ${KEYCLOAK_INTERNAL_USERS_URL:}
    client-id: ${KEYCLOAK_CLIENT_ID:}
    username: ${KEYCLOAK_ADMIN:}
    password: ${KEYCLOAK_ADMIN_PASSWORD:}
